//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebshopDbEntities1 : DbContext
    {
        public WebshopDbEntities1()
            : base("name=WebshopDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Lt_OrderProduct> Lt_OrderProduct { get; set; }
        public DbSet<OrderInfo> OrderInfoes { get; set; }


    }

    public class OrderViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Phonenumber")]
        public int Phone { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Zipcode")]
        public string ZipCode { get; set; }

        [Required]
        [Display(Name = "Street")]
        public string Street { get; set; }
    }
}
