//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebshopDbEntities : DbContext
    {
        public WebshopDbEntities()
            : base("name=WebshopDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Lt_OrderProduct> Lt_OrderProduct { get; set; }
        public DbSet<OrderInfo> OrderInfoes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<UserEmail> UserEmails { get; set; }
    }
}
